---
- name: Create /srv directory
  file: path=/srv/ state=directory

- name: Create image
  shell: "truncate --size=2G /srv/test.brick{{ item }}.img"
  with_sequence: count={{ devices_count }}

- name: Create xfs on image
  shell: "mkfs -t xfs /srv/test.brick{{ item }}.img"
  with_sequence: count={{ devices_count }}

- name: Create mount point
  file: path=/bricks/b{{ item }} state=directory
  with_sequence: count={{ devices_count }}

- name: Mount image
  shell: "mount -o loop /srv/test.brick{{ item }}.img /bricks/b{{ item }}"
  with_sequence: count={{ devices_count }}

- name: Create data dir
  file: path=/bricks/b{{ item }}/data state=directory
  with_sequence: count={{ devices_count }}
