# Request 1 CentOS 7 x86_64 node (for build_server)
---
- hosts: localhost
  connection: local
  pre_tasks:
    - cico:
        action=get
        api_key={{ api_key }}
        arch=x86_64
        release=7
        count=1
      register: data

    - debug: msg="Host {{ item.key }} has this ssid {{ item.value.comment }}"
      with_dict: "{{ data.results.hosts }}"

    - name: Add one host to qe_server group
      add_host:
        name="{{ data.results.hosts.keys()[0] }}"
        groups="build_server"

  roles:
    - role: saveinventory
    - role: savessids
      tendrlhosts: "{{ data.results.hosts }}"

- hosts: build_server
  remote_user: root
  tasks:
  - name: Add EPEL repository
    yum: name="epel-release" state=latest

  # WORKAROUND for BZ 1492610
  - name: "WORKAROUND: BZ 1492610 - Install bodhi"
    yum: name="{{ item }}" state=latest
    with_items:
    - "https://kojipkgs.fedoraproject.org//packages/bodhi/2.10.1/2.el7/noarch/bodhi-client-2.10.1-2.el7.noarch.rpm"
    - "https://kojipkgs.fedoraproject.org//packages/bodhi/2.10.1/2.el7/noarch/python2-bodhi-2.10.1-2.el7.noarch.rpm"

  - name: Install required packges
    yum: name="{{ item }}" state=latest
    with_items:
    - copr-cli
    - createrepo
    - fedpkg
    - fontconfig
    - git
    - mock
    - nodejs
    - nodejs-packaging
    - npm
    - rpm-build
    - ruby
    - rubygem-bundler
    - vim

  - name: Create mock user
    user:
      name: mock
      group: mock
