# Request 1 CentOS 7 x86_64 node (for build_server)
---
- hosts: localhost
  connection: local
  pre_tasks:
    - cico:
        action=get
        api_key={{ api_key }}
        arch=x86_64
        release=7
        count=1
      register: data

    - debug: msg="Host {{ item.key }} has this ssid {{ item.value.comment }}"
      with_dict: "{{ data.results.hosts }}"

    - name: Add one host to qe_server group
      add_host:
        name="{{ data.results.hosts.keys()[0] }}"
        groups="build_server"

  roles:
    - role: saveinventory
    - role: savessids
      tendrlhosts: "{{ data.results.hosts }}"

- hosts: build_server
  remote_user: root
  tasks:
  - name: Add EPEL repository
    yum: name="epel-release" state=latest

  - name: WORKAROUND - install http-parser
    shell: 'yum install -y http://springdale.math.ias.edu/data/puias/unsupported/7/x86_64//http-parser-2.7.1-3.sdl7.x86_64.rpm'

  - name: Install required packges
    yum: name="{{ item }}" state=latest
    with_items:
    - copr-cli
    - fedpkg
    - fontconfig
    - git
    - nodejs
    - nodejs-packaging
    - npm
    - rpm-build
    - ruby
    - rubygem-bundler
    - vim
