# Request 3 CentOS 7 x86_64 nodes
---
- hosts: localhost
  connection: local
  pre_tasks:
    - cico:
        action=get
        api_key={{ api_key }}
        arch=x86_64
        release=7
        count=6
      register: data
    
    - debug: msg="Host {{ item.key }} has this ssid {{ item.value.comment }}"
      with_dict: "{{ data.results.hosts }}"
  
  roles: 
    - role: saveinventory
      tendrlhosts: "{{ data.results.hosts.keys() }}"
      clustername: clustername
    - role: savessids
      tendrlhosts: "{{ data.results.hosts }}"
      clustername: clustername
