# Release nodes requested in a registered 'get' action
---
- hosts: localhost
  connection: local 
  vars:
    - ssid: "{{ lookup('csvfile', '{} file={} delimiter=,'.format(clustername, home_dir + clustername + '.ssid')) }}"
  tasks: 
    - debug: msg="{{ ssid }}"

    - cico:
        action=done
        api_key="{{ api_key }}"
        ssid="{{ ssid }}"
