---
- hosts: localhost
  connection: local
  vars:
    - ssid: "{{ lookup('csvfile', '{} file={} delimiter=,'.format(clustername, home_dir + clustername + '.ssid')) }}"
  pre_tasks: 
    - cico:
        action=list
        ssid="{{ ssid }}"
      register: data

    - debug: msg="Host {{ item.key }} is {{ item.value.architecture }}"
      with_dict: "{{ data.results.hosts }}"

  roles: 
    - role: saveinventory
      tendrlhosts: "{{ data.results.hosts.keys() }}"
      clustername: clustername
    - role: savessids
      tendrlhosts: "{{ data.results.hosts }}"
      clustername: clustername
