# Request 1 CentOS 7 x86_64 node (for qe_server)
---
- hosts: localhost
  connection: local
  pre_tasks:
    - cico:
        action=get
        api_key={{ api_key }}
        arch=x86_64
        release=7
        count=1
      register: data
    
    - debug: msg="Host {{ item.key }} has this ssid {{ item.value.comment }}"
      with_dict: "{{ data.results.hosts }}"
  
    - name: Add one host to qe_server group
      add_host:
        name="{{ data.results.hosts.keys()[0] }}"
        groups="qe_server"

  roles:
    - role: saveinventory
    - role: savessids
      tendrlhosts: "{{ data.results.hosts }}"
